const products=[
 {id:515291,article:'200300285_',name:'027228 АВ DRX250 MT 3ф 160А 18kA Legrand',price:64920,stock:23,cert:'https://ekt.kz/catalog/nizkovoltnaya_apparatura/silovye_avtomaticheskie_vyklyuchateli/drx250_mt_10_250_a_legrand/027228_av_drx250_mt_3f_160a_18ka_legrand_1/',spec:'3 полюса · 160А · 18kA · 400В AC · Legrand'},
 {id:48783,article:'200300286_',name:'АВ DRX250 3ф 125А 18kA Legrand',price:58700,stock:11,cert:null,spec:'3 полюса · 125А · 18kA · 400В AC · Legrand'},
 {id:45357,article:'ярп4520',name:'LED STARK 30W 2400Lm d98×180 4000K IP20 MEGALIGHT',price:1810,stock:0,cert:null,spec:'30Вт · 2400Лм · 4000К · IP20 · MEGALIGHT'},
 {id:45102,article:'ml-spot-30',name:'Светильник трековый 30W 2400Lm 4000K IP20 MEGALIGHT',price:2190,stock:48,cert:null,spec:'30Вт · 2400Лм · 4000К · IP20 · MEGALIGHT'}
];
let cart=[],pending=null;const el=id=>document.getElementById(id),talk=el('conversation');
function money(n){return new Intl.NumberFormat('ru-RU').format(n)+' ₸'}
function say(text,who='assistant'){const d=document.createElement('div');d.className='message '+who;d.innerHTML=text;talk.append(d);talk.scrollTop=talk.scrollHeight}
function productCard(p,reason=''){const t=el('productTemplate').content.cloneNode(true);t.querySelector('.availability').textContent=p.stock?`В наличии: ${p.stock} шт.`:'Нет в наличии';t.querySelector('.article').textContent='Артикул '+p.article;t.querySelector('h3').textContent=p.name;t.querySelector('.product-meta').textContent=(reason?reason+' · ':'')+p.spec;t.querySelector('strong').textContent=money(p.price);t.querySelector('.select-product').onclick=()=>offer(p,1);return t}
function showProduct(p,reason){const wrapper=document.createElement('div');wrapper.append(productCard(p,reason));talk.append(wrapper);talk.scrollTop=talk.scrollHeight}
function offer(p,qty){if(!p.stock){say('<strong>Этой позиции сейчас нет в наличии.</strong> Могу предложить аналог:');showProduct(products.find(x=>x.id===45102),'Похожая мощность и световой поток');return}pending={p,qty:Math.min(qty,p.stock)};say(`<strong>Подтверждение нужно перед добавлением</strong>${p.name}<br>${pending.qty} шт. × ${money(p.price)}. Напишите <b>«Да, добавь»</b>, чтобы положить товар в корзину.`)}
function renderCart(){const wrap=el('cartItems');wrap.innerHTML='';if(!cart.length){wrap.innerHTML='<p class="empty">Пока пусто</p>';el('cartCount').textContent='0 товаров';el('checkout').classList.add('disabled');return}cart.forEach(i=>{const d=document.createElement('div');d.className='cart-row';d.innerHTML=`<b>${i.p.name}</b><span>${i.qty} шт. · ${money(i.qty*i.p.price)}</span>`;wrap.append(d)});el('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0)+' товаров';const a=el('checkout');a.classList.remove('disabled');a.href='https://ekt.kz/basket/';}
function addPending(){if(!pending)return;say(`Готово — добавила <b>${pending.p.name}</b>, ${pending.qty} шт. в корзину. <a href="https://ekt.kz/basket/" target="_blank">Перейти к оформлению →</a>`);const found=cart.find(x=>x.p.id===pending.p.id);found?found.qty+=pending.qty:cart.push(pending);pending=null;renderCart()}
function answer(raw){const q=raw.toLowerCase().trim();say(raw,'user');if(/^(да[, ]*)?(добавь|добавить|подтверждаю)|^да$/.test(q)&&pending){addPending();return}if(/достав|оплат|минимальн|услов/.test(q)){say('<strong>Условия покупки</strong>Оплата и доставка уточняются при оформлении заказа. Минимальная партия указана в карточке товара; для большинства позиций в прототипе — от 1 штуки. Я не запрашиваю платёжные данные в чате.');return}let p=products.find(x=>q.includes(x.article.toLowerCase())||q.includes('027228')||q.includes('drx250'))||products.find(x=>q.includes('stark')||q.includes('светильник'));if(p){if(p.stock){say(`<strong>Нашла товар</strong>В наличии ${p.stock} шт. ${p.cert?`<br><a href="${p.cert}" target="_blank">Открыть карточку и сертификаты →</a>`:''}`);showProduct(p);if(/добав|корзин|шт|штук/.test(q)){const n=Number(q.match(/(\d+)\s*(?:шт|штук)/)?.[1])||1;offer(p,n)}return}say('<strong>Проверила остатки</strong>Этого товара сейчас нет. Предлагаю релевантный аналог — с такой же мощностью и световым потоком.');showProduct(products.find(x=>x.id===45102),'Причина: аналог 30Вт / 2400Лм / 4000К');return}say('Я могу найти товар по артикулу или названию, проверить остаток, подобрать аналог и рассказать об условиях покупки. Например: «Есть ли 027228?»')}
el('chatForm').onsubmit=e=>{e.preventDefault();const input=el('message');if(input.value.trim()){answer(input.value);input.value=''}};el('quickActions').onclick=e=>{if(e.target.dataset.query)answer(e.target.dataset.query)};say('<strong>Здравствуйте! Я AI‑консультант ekt.</strong>Помогу с каталогом, техническими характеристиками, наличием и аналогами. Напишите артикул или название товара.');renderCart();
